
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgfsyayitqlelvtjresx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZnN5YXlpdHFsZWx2dGpyZXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTcyMzMsImV4cCI6MjA2MjQ3MzIzM30.DUEdiSMKwd8BSZsNMK_EHMJK_RDo-LAo7YEP_4rGo7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Initialize the storage bucket if it doesn't exist yet
const initializeStorage = async () => {
  try {
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    // Check if selfies bucket exists
    const selfiesBucketExists = buckets?.some(bucket => bucket.name === 'selfies');
    
    if (!selfiesBucketExists && !error) {
      console.log("Creating selfies bucket...");
      await supabase.storage.createBucket('selfies', {
        public: true,
        fileSizeLimit: 5242880, // 5MB limit
        allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp']
      });
      console.log("Selfies bucket created successfully!");
    }
  } catch (err) {
    console.error("Error initializing storage:", err);
  }
};

// Call the initialization function
initializeStorage();
